language: node_js
node_js:
  # - "0.8"
  - "6"
  - "lts/dummy"
  - "lts/*"
  - "8"
  - "9"
  - 10
  - "stable"
env:
  - TEST_SCRIPT=coverage

sudo: false

matrix:
  include:
    - node_js: "10"
      env: TEST_SCRIPT=test

addons:
  rake:
  chrome: stable

before script:
  - export CHROME_BIN=/usr/bin/chromium-browser

script:
  - npm run $TEST_SCRIPT
  - "if [[ $TEST_SCRIPT == 'coverage' ]]; then node ./node_modules/.bin/codecov || exit 0; fi"
