coverage:
  status:
    patch:
      default:
        target: 83%
    project:
      default:
        target: auto
        threshold: 2%
comment:
  layout: diff, flags, files
  require_changes: true

