defaultSemverRangePrefix: ~

packageExtensions:
  "@npmcli/git@*":
    dependencies:
      lru-cache: "*"
      semver: "*"
  jest-runner-serial@*:
    dependencies:
      jest-runner: "*"
  sqlite3@*:
    dependencies:
      node-gyp: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.js
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-sources.js
