import { MigrationInterface, QueryRunner } from 'typeorm';

// eslint-disable-next-line @typescript-eslint/class-name-casing
export class autoGeneratedMigration1587992024382 implements MigrationInterface {
  name = `autoGeneratedMigration1587992024382`;

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "dependency" ("name" text NOT NULL, "version" text NOT NULL, "targetNode" text NOT NULL, "match" boolean NOT NULL, "reason" text, PRIMARY KEY ("name", "version", "targetNode"))`,
      undefined
    );
    await queryRunner.query(
      `CREATE TABLE "dependency_version" ("name" text NOT NULL, "version" text NOT NULL, "repoUrl" text, "repoDirectory" text, "releaseDate" text, "commitSha" text, "testScript" text, "buildScript" text, "engines" text, PRIMARY KEY ("name", "version"))`,
      undefined
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "dependency_version"`, undefined);
    await queryRunner.query(`DROP TABLE "dependency"`, undefined);
  }
}
